### ISSUE TITLE
Bug Report: Camera Scrolling and Menu Movement is tied to FPS cap

### ISSUE THREAD

**Issue by IoMarz** [KadeDev/vswhitty-public#4]
OS: Arch Linux 
Engine: Kade Engine 1.4.2

I am using a 150FPS cap, and it seems like the camera scroll speeds and menu screen speeds are messed up.
The camera scroll speed issue seems to happen only sometimes, but the main menu speed issue is constant 

The main menu speed issue can be seen in this clip here:
https://user-images.githubusercontent.com/56744673/119581572-d287fd80-bd90-11eb-8dd2-9ff41a7f2b28.mp4

**Comment by Kade-github** [comment]
kinda intentional I guess? I noticed this a while back and I just liked it like this way.
