### ISSUE TITLE
Suggestion: Put the non-updated version.

### ISSUE THREAD

**Issue by yardmith** [KadeDev/vswhitty-public#6]
Suggestion: Put the source code for the original VS Whitty version; i.e. the version that isn't updated to 1.4.2 Kade Engine.

**Comment by Kade-github** [comment]
no

**Comment by ghost** [comment]
I af=gree with this'
New ballistic sucks

**Comment by ADuckInBlack** [comment]
> I af=gree with this'
> New ballistic sucks

then play old ballistic

**Comment by ghost** [comment]
There isn't the old ballistic source though.

**Comment by ADuckInBlack** [comment]
have you checked freeplay?

**Comment by ghost** [comment]
thats new ballistic im pretty sure

**Comment by ADuckInBlack** [comment]
> There isn't the old ballistic source though.

oh

**Comment by ghost** [comment]
nevermind
old ballistic is in freeplay
