### ISSUE TITLE
Whitty Mod Crash

### ISSUE THREAD

**Issue by ADuckInBlack** [KadeDev/vswhitty-public#7]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

Hi, Kade! I know this might be a dumb and inconvenient way of writing a bug report, but I find
this to be the easiest way to write things down in the correct format.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

I am using Windows (x64) OS with an Intel Core i5 CPU (if that's necessary).

## What version of the game are you using? Look in the bottom left corner of the main menu.

I'm playing v690. (great version name btw lol)

I'ma make an edit real quick, and say that I forgot to add the actual version in the corner of the menu, which is
FNF version (0.2.7.1), and Kade version (1.4.2.). My mistake!

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

I play any song. I don't think there was anything else.

## Please describe your issue. Provide extensive detail and images if possible.

Well, the issue is that every time I try playing a song, the game commits suicide (, or in other words: the game crashes).

I'm not entirely sure what to do. I WOULD maybe try reinstall the Kade engine, but that would take big brain to figure that
one out. I'm not sure if this is my fault, a problem with my PC, or a programming error, but hey.  That's why I'm here, I guess.

Thanks, Kade!

**Comment by Kade-github** [comment]
yeah so I don't maintain v690, I maintain v142. Thats BBPanzu who made that, and its a teaser update not the actual well update. I'll probably reupload it as a different name.

**Comment by ADuckInBlack** [comment]
Oh. Okay! Thanks for telling me. I understand now.

I'm going to install v142 next time, if I want to play
Whitty Mod.

Take care!

**Comment by ADuckInBlack** [comment]
idk why, but i felt obligated to have good grammar here
