### ISSUE TITLE
Enhancement: Can You add Cloud Man

### ISSUE THREAD

**Issue by Lamba2** [KadeDev/vswhitty-public#9]
can you add cloud man in a other folder which is the version which crashes if you select any other week  execpt ? week in  totally normal mirror

**Comment by ADuckInBlack** [comment]
kade doesn't maintain that version. sorry!

**Comment by Lamba2** [comment]
> kade doesn't maintain that version. sorry!

Oh well can he ask to get it from bbpanzu

**Comment by ADuckInBlack** [comment]
> > kade doesn't maintain that version. sorry!
> 
> Oh well can he ask to get it from bbpanzu

maybe, actually
i'm not to say, though
you'd have to ask him

**Comment by Lamba2** [comment]
how would  i  do that

**Comment by gamerbross** [comment]
> can you add cloud man in a other folder which is the version which crashes if you select any other week execpt ? week in totally normal mirror

I spoke to bbpanzu to ask him about the src and he uploaded it lol
https://github.com/bbpanzu/FNF-Updike-Source

**Comment by ADuckInBlack** [comment]
> > can you add cloud man in a other folder which is the version which crashes if you select any other week execpt ? week in totally normal mirror
> 
> I spoke to bbpanzu to ask him about the src and he uploaded it lol
> https://github.com/bbpanzu/FNF-Updike-Source

sick
